version: 2

models:
  - name: dim_apps
    columns:
      - name: app_key
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique
      - name: date_day
        tests:
          - not_null
          - unique

  - name: fact_reviews
    columns:
      - name: review_id
        tests:
          - not_null
          - unique
      - name: app_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_apps')
                field: app_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_key
      - name: score
        tests:
          - not_null